### ISSUE TITLE
unable to commit documents to Solr

### ISSUE THREAD

**Issue by joettt** [Norconex/committer-solr#10]
[minimum-config.txt](https://github.com/Norconex/committer-solr/files/705232/minimum-config.txt)

I have created a new collection and modified the committer section in the attached config file to add the test page to this collection but running collector-http.bat does not add the document to the collection.   Can you please tell me what I am doing wrong?

Thanks

**Comment by essiembre** [comment]
Do you have any errors in the HTTP Collector logs?  If unsure, can you attach it?   Also, do you have errors in your Solr logs?

**Comment by joettt** [comment]
Please find attached the HTTP collector and solr logs.  Thanks.

[201701131444200889__Norconex_32_Minimum_32_Test_32_Page.log.txt](https://github.com/Norconex/committer-solr/files/705465/201701131444200889__Norconex_32_Minimum_32_Test_32_Page.log.txt)

[solr.log.txt](https://github.com/Norconex/committer-solr/files/705468/solr.log.txt)

**Comment by essiembre** [comment]
The collector log tells you the document is "REJECTED_UNMODIFIED".  This mean on a subsequent run, it checked and was not modified from a previous run so it won't send it to Solr.   To start from scratch, you need to delete the crawl database before restarting it ("crawlstore" folder).  Or you could just delete the "workdir" (./examples-output/minimum according to config).   You should see something different in the log this time.  If you see COMMITED_ADD, it means it reached the Solr Committer and Solr should eventually receive it.

**Comment by joettt** [comment]
Thanks for all your help.  When I delete the crawl database, I do see COMMITTED_ADD but the problem I have been having is I don't see it in my collection.  I am attaching the screen shot of solr admin & the log files:

![solr](https://cloud.githubusercontent.com/assets/25109305/21969575/502703b8-db6d-11e6-8975-1fc4501e22c4.jpg)


[Norconex_32_Minimum_32_Test_32_Page.log.txt](https://github.com/Norconex/committer-solr/files/707152/Norconex_32_Minimum_32_Test_32_Page.log.txt)
[solr.log2.txt](https://github.com/Norconex/committer-solr/files/707154/solr.log2.txt)

**Comment by essiembre** [comment]
I see nothing wrong in your logs.  The Solr Committer did its job and successfully sent it to Solr or you would get an error.   So if there was a problem, it is on the Solr side, but the Solr logs look like it was processed.   What if you execute a query for ``*:*`` on Solr on that collection?  What do you get?

**Comment by joettt** [comment]
http://localhost:8983/solr/mycollection1/select?indent=on&q=Norconex&wt=json

{
  "responseHeader":{
    "status":0,
    "QTime":0,
    "params":{
      "q":"Norconex",
      "indent":"on",
      "wt":"json",
      "_":"1484590546928"}},
  "response":{"numFound":0,"start":0,"docs":[]
  }}

**Comment by joettt** [comment]
{
  "responseHeader":{
    "status":0,
    "QTime":0,
    "params":{
      "q":"*:*",
      "indent":"on",
      "wt":"json",
      "_":"1484590819486"}},
  "response":{"numFound":0,"start":0,"docs":[]
  }}

**Comment by joettt** [comment]
what is the http request to commit a document to Solr?  Perhaps I could run that query on mycollection1 and see if there are any messages.

**Comment by essiembre** [comment]
Good idea.  See if you can add any document manually first.    There are few different ways to add a document manually.  Here is an example: http://www.solrtutorial.com/solr-in-5-minutes.html#Indexing

Also, I do not know how you configured your Solr, but maybe you need to force a Solr commit:
``<URL_TO_YOUR_COLLECTION>/update?commit=true``

**Comment by joettt** [comment]
I can add documents to techproducts using post.jar but not through the committer even after trying solr commit to the collection.

**Comment by joettt** [comment]
the solr tutorial page mentions HTTP client as one way to add data to solr.  Do you know what the http command is to add data to a solr collection?

**Comment by essiembre** [comment]
You will find here the expected XML/JSON format and examples how to send them to Solr using Curl: https://cwiki.apache.org/confluence/display/solr/Uploading+Data+with+Index+Handlers

**Comment by essiembre** [comment]
Having a second look at your logs, I can tell those are the logs from Solr after it was restarted on Jan 16.  The crawler log you have attached is from Jan 15.  So if there were Solr indexing errors, they would appear in the logs you attached.  Start Solr, run the collector from scratch, wait a little and then check/send the Solr logs.

**Comment by joettt** [comment]
It seems the Solr clock is 5 hours ahead as it is again showing the log entries five hours ahead.  Please find attached the latest Solr & collector logs.

[solr.log.txt](https://github.com/Norconex/committer-solr/files/709927/solr.log.txt)
[Norconex_32_Minimum_32_Test_32_Page.log.txt](https://github.com/Norconex/committer-solr/files/709929/Norconex_32_Minimum_32_Test_32_Page.log.txt)

**Comment by essiembre** [comment]
Do you have other logs under Solr, and are you sure you configured the Solr Committer properly.  I looked at your original config attached earlier, and you reference a collection named "collection1" but in Solr logs, only "mycollection1" appears to exist.  Make sure they are the same.  If your config changed since you posted the logs, please attach it again.

**Comment by essiembre** [comment]
Normally if your Solr Committer is configured properly, you should see a line starting with "INFO  [AbstractCollector] Version: "SolrCommitter" [...]" in your log.  I do not see it.

**Comment by joettt** [comment]
Reinstalled Solr, Norconnex connector & committer.  It all works now.  Thank you for helping me on  it.

**Comment by essiembre** [comment]
Great! Thanks for confirming.
