### ISSUE TITLE
Update Documents

### ISSUE THREAD

**Issue by angelo337** [Norconex/committer-solr#12]
hi there:
I have a question please, is it possible to update a document that is on solr index but not delete all current information that is store in there? I mean, i have around 8K URL but just some change 1 field or 2 and I would like to update just that fields and keep all current information indexed, is it possible?
thanks a lot

**Comment by essiembre** [comment]
If your schema supports it, Solr supports partial document updates.  Have a look here: https://lucene.apache.org/solr/guide/6_6/updating-parts-of-documents.html

**Comment by angelo337** [comment]
thanks a lot
that's what I am looking for
