### ISSUE TITLE
[Q] How can Solr committer be configured when Solr employes basic authentication

### ISSUE THREAD

**Issue by ohtwadi** [Norconex/committer-solr#17]
Hello,

Our Solr instance employs basic authentication. This means that all clients need to specify valid credentials for communication. Further details can be found at https://lucene.apache.org/solr/guide/8_0/basic-authentication-plugin.html#BasicAuthenticationPlugin-UsingBasicAuthwithSolrJ

Is this supported in Solr committer?

Thanks!

**Comment by essiembre** [comment]
It is not in there at the moment but I am marking it as a feature request.

**Comment by essiembre** [comment]
Please try the [latest snapshot](http://www.norconex.com/collectors/committer-solr/download) and confirm.  It is now possible to perform BASIC authentication.  Check out [usage documentation](http://www.norconex.com/collectors/committer-solr/latest/apidocs/com/norconex/committer/solr/SolrCommitter.html).

**Comment by essiembre** [comment]
Released.
