### ISSUE TITLE
Upgrade  solrj library from solrj-4.7.0 to solrj-5.0.0 and test the committer-solr with Solr 3.x Solr 4.x Solr 5.x and SolrCloud

### ISSUE THREAD

**Issue by martinfou** [Norconex/committer-solr#2]

**Comment by martinfou** [comment]
This request has been complete and is part of the commit id 
89c89dce671acecfab1861b35979baffcfbe8c95

**Comment by essiembre** [comment]
Let's leave this ticket open until the next official release.  If you confirm your fix has been committed, please set the Fix/Done label until then.

**Comment by martinfou** [comment]
The pom.xml file did not get commited last time around.

It is fixed now with this commit.

https://github.com/Norconex/committer-solr/commit/5514cce46c9fa30d5d7c577c1dfcd0293c60951c

**Comment by essiembre** [comment]
[Snapshot release](http://www.norconex.com/collectors/committer-solr/download) of Solr Commiter now has this fix.

**Comment by essiembre** [comment]
Stable release 2.0.1 is now out with this fix: http://www.norconex.com/collectors/committer-solr/download.
